server:
  port: 9080
spring:
  datasource:
    username: sa
    password: sa
    url: jdbc:h2:mem:default;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher